# Generated by Django 4.2 on 2023-04-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Content',
            new_name='content',
        ),
    ]
